# Generated by Django 5.1.3 on 2026-03-18 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_advertising_batch_and_indexes'),
        ('website_advertising', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['book', 'location', 'start_date', 'end_date'], name='website_adv_book_id_405dec_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['user', '-created_at'], name='website_adv_user_id_5c330c_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['location', 'start_date', 'end_date'], name='website_adv_locatio_eae3be_idx'),
        ),
    ]
