# Generated by Django 5.1.3 on 2026-03-21 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_advertising_batch_and_indexes'),
        ('website_advertising', '0003_advertisement_search_targeting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='advertisement',
            new_name='website_adv_book_id_58a7de_idx',
            old_name='website_adv_book_loc_tg_d_idx',
        ),
        migrations.RenameIndex(
            model_name='advertisement',
            new_name='website_adv_locatio_e89365_idx',
            old_name='website_adv_loc_tg_dates_idx',
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['location', 'is_active', 'start_date', 'end_date'], name='website_adv_loc_act_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['location', 'is_active', 'target_kind', 'target_id'], name='website_adv_loc_act_tgt_idx'),
        ),
    ]
