# Generated by Django 5.1.3 on 2026-01-06 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operation_type', models.CharField(choices=[('deposit', 'Поповнення'), ('withdraw', 'Виведення')], max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Завершено'), ('failed', 'Помилка')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Журнал операцій з балансом',
                'verbose_name_plural': 'Журнал операцій з балансом',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('is_purchased', models.BooleanField(default=False)),
                ('scroll_position', models.FloatField(default=0)),
                ('reading_time', models.IntegerField(default=0)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('reading_speed', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Прогрес читання',
                'verbose_name_plural': 'Прогрес читання',
            },
        ),
        migrations.CreateModel(
            name='AdvertisingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('main', 'Реклама на Головній'), ('genres', 'Реклама у Пошуку за жанрами'), ('tags', 'Реклама у Пошуку за тегами'), ('fandoms', 'Реклама у Пошуку за фендомами')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertising_logs', to='catalog.book')),
            ],
            options={
                'verbose_name': 'Журнал реклами',
                'verbose_name_plural': 'Журнал реклами',
                'ordering': ['-created_at'],
            },
        ),
    ]
