# Generated by Django 5.1.3 on 2026-01-06 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('monitoring', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisinglog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertising_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balanceoperationlog',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_operations', to='users.profile'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='users.profile'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.chapter'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='users.profile'),
        ),
        migrations.AddField(
            model_name='userchapterprogress',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='catalog.chapter'),
        ),
        migrations.AddField(
            model_name='userchapterprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userchapterprogress',
            index=models.Index(fields=['user', 'chapter'], name='monitoring__user_id_bba2fd_idx'),
        ),
        migrations.AddIndex(
            model_name='userchapterprogress',
            index=models.Index(fields=['is_read'], name='monitoring__is_read_a8bd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='userchapterprogress',
            index=models.Index(fields=['is_purchased'], name='monitoring__is_purc_252af2_idx'),
        ),
        migrations.AddIndex(
            model_name='userchapterprogress',
            index=models.Index(fields=['user', 'is_read'], name='monitoring__user_id_e0e925_idx'),
        ),
        migrations.AddIndex(
            model_name='userchapterprogress',
            index=models.Index(fields=['user', 'is_purchased'], name='monitoring__user_id_847d11_idx'),
        ),
        migrations.AddIndex(
            model_name='userchapterprogress',
            index=models.Index(fields=['chapter', 'is_read'], name='monitoring__chapter_251720_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userchapterprogress',
            unique_together={('user', 'chapter')},
        ),
    ]
