# Generated by Django 5.1.3 on 2026-03-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisinglog',
            name='location',
            field=models.CharField(choices=[('main', 'Реклама на Головній'), ('catalog', 'Реклама на Каталозі'), ('genres', 'Реклама у Пошуку за жанрами'), ('tags', 'Реклама у Пошуку за тегами'), ('fandoms', 'Реклама у Пошуку за фендомами')], max_length=20),
        ),
    ]
