# Generated by Django 5.1.3 on 2026-03-19 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_advertising_batch_and_indexes'),
        ('monitoring', '0004_transactionlog_chapter_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='chapter',
            field=models.ForeignKey(blank=True, help_text='Null для покупки пакета підписки (prepaid/bulk)', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.chapter'),
        ),
    ]
