# Generated by Django 5.1.3 on 2026-05-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_authorthanks_idempotency_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запис транзакції', 'verbose_name_plural': 'Журнал транзакцій'},
        ),
        migrations.AlterField(
            model_name='balanceoperationlog',
            name='operation_type',
            field=models.CharField(choices=[('deposit', 'Поповнення'), ('withdraw', 'Виведення'), ('refund', 'Повернення')], max_length=20),
        ),
    ]
