# Generated by Django 5.1.3 on 2026-04-09 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_total_characters'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceIdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('operation_type', models.CharField(choices=[('deposit', 'deposit'), ('withdraw', 'withdraw')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_idempotency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='uniq_balance_idempotency_user_key')],
            },
        ),
    ]
