# Generated by Django 5.1.3 on 2026-05-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_balanceidempotencyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancelog',
            name='operation_type',
            field=models.CharField(choices=[('deposit', 'Поповнення'), ('withdraw', 'Виведення'), ('purchase', 'Покупка'), ('earning', 'Заробіток'), ('advertising', 'Реклама'), ('refund', 'Повернення')], max_length=20),
        ),
    ]
