# Generated by Django 5.1.3 on 2026-05-20 17:29

from django.db import migrations, models


def fix_negative_balances(apps, schema_editor):
    """Обнуляє від'ємні баланси перед додаванням constraint."""
    Profile = apps.get_model('users', 'Profile')
    count = Profile.objects.filter(balance__lt=0).update(balance=0)
    if count:
        print(f"\n  WARNING: zeroed {count} negative-balance profile(s)")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_add_balance_non_negative_constraint'),
        ('users', '0006_alter_balancelog_operation_type'),
    ]

    operations = [
        migrations.RunPython(fix_negative_balances, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='balance_non_negative'),
        ),
    ]
