# Generated by Django 5.1.3 on 2026-05-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_balance_non_negative_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancelog',
            name='operation_type',
            field=models.CharField(choices=[('deposit', 'Поповнення'), ('withdraw', 'Виведення'), ('purchase', 'Покупка'), ('earning', 'Заробіток'), ('advertising', 'Реклама'), ('refund', 'Повернення'), ('thanks_given', 'Подяка (списання)'), ('thanks_received', 'Подяка (зарахування)')], max_length=20),
        ),
    ]
