# Generated by Django 5.1.3 on 2026-06-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_balancelog_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancelog',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Опис операції'),
        ),
    ]
