# Generated by Django 5.1.3 on 2026-03-05 18:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='_position',
            field=models.DecimalField(blank=True, db_column='position', decimal_places=1, default=Decimal('0'), max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ChapterOrderContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_order_containers', to='catalog.book')),
                ('volume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_order_containers', to='catalog.volume')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('volume__isnull', False)), fields=('book', 'volume'), name='uniq_chapter_container'), models.UniqueConstraint(condition=models.Q(('volume__isnull', True)), fields=('book',), name='uniq_chapter_container_no_vol')],
            },
        ),
    ]
