# Generated by Django 5.1.3 on 2026-04-09 10:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_chapter_slug_unique_per_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1000.00'))], verbose_name='Вартість розділу'),
        ),
    ]
