# Generated by Django 5.1.3 on 2026-04-11 18:18

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_chapter_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='content_json',
            field=models.JSONField(blank=True, help_text='Основне джерело контенту глави', null=True, verbose_name='Структурований контент (ProseMirror JSON)'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='content_version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версія контенту'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.catalog.models.chapter_directory_path, verbose_name='Оригінальний завантажений файл'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='original_file_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Тип оригінального файлу (docx, editor)'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='plain_text',
            field=models.TextField(blank=True, null=True, verbose_name='Чистий текст для пошуку'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='plain_text_length',
            field=models.IntegerField(default=0, verbose_name='Кількість символів чистого тексту'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='rendered_html',
            field=models.TextField(blank=True, null=True, verbose_name='HTML для відображення (генерується автоматично)'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='toc_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Зміст (заголовки глави)'),
        ),
    ]
