# Generated by Django 5.1.3 on 2026-05-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_chapter_content_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='character_count',
            field=models.IntegerField(default=0, help_text='Канонічна кількість символів (plain text); characters_count дублює для сумісності.'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='characters_count',
            field=models.IntegerField(default=0, help_text='Застаріле ім’я поля; синхронізується з character_count автоматично.', verbose_name='Кількість символів'),
        ),
    ]
