# Generated by Django 5.1.3 on 2026-05-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_add_balance_non_negative_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order'], 'verbose_name': 'Глава', 'verbose_name_plural': 'Глави'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Країна', 'verbose_name_plural': 'Країни'},
        ),
        migrations.AlterModelOptions(
            name='fandom',
            options={'verbose_name': 'Фандом', 'verbose_name_plural': 'Фандоми'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанри'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='taggroups',
            options={'verbose_name': 'Група тегів', 'verbose_name_plural': 'Групи тегів'},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Том', 'verbose_name_plural': 'Томи'},
        ),
    ]
