# Generated by Django 5.1.3 on 2026-06-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_book_options_alter_chapter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='fandoms',
            field=models.ManyToManyField(blank=True, to='catalog.fandom'),
        ),
    ]
