# Generated by Django 5.1.3 on 2026-06-20 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_book_options_alter_chapter_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='fandoms',
            field=models.ManyToManyField(blank=True, to='catalog.fandom'),
        ),
        migrations.CreateModel(
            name='TranslatorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Очікує розгляду'), ('APPROVED', 'Схвалено'), ('REJECTED', 'Відхилено')], default='PENDING', max_length=20, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата розгляду')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translator_applications', to='catalog.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translator_applications', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Заявка на переклад',
                'verbose_name_plural': 'Заявки на переклад',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('book', 'user'), name='unique_pending_application_per_user_book')],
            },
        ),
    ]
