# Generated by Django 5.1.3 on 2026-06-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_translator_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='translation_status',
            field=models.CharField(blank=True, choices=[('TRANSLATING', 'Перекладається'), ('WAITING', 'В очікуванні розділів'), ('COMPLETED', 'Завершено'), ('PAUSED', 'Перерва'), ('ABANDONED', 'Покинутий')], max_length=20, null=True, verbose_name='Статус перекладу'),
        ),
    ]
