# Generated by Django 5.1.3 on 2026-06-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_book_fandoms'),
        ('catalog', '0016_add_completed_translation_status'),
    ]

    operations = [
    ]
