# Generated by Django 5.1.3 on 2026-06-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_add_completed_translation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTranslatorReview',
            fields=[
            ],
            options={
                'verbose_name': 'Заявка на переклад',
                'verbose_name_plural': 'Заявки на переклад',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.book',),
        ),
    ]
