# Generated by Django 5.1.3 on 2026-06-25 19:20

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_booktranslatorreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.catalog.models.book_gallery_image_path, validators=[apps.catalog.models.validate_image_extension])),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Порядковий номер слоту (0–4)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.book')),
            ],
            options={
                'verbose_name': 'Додаткове зображення книги',
                'verbose_name_plural': 'Додаткові зображення книг',
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('book', 'position'), name='unique_book_image_position'), models.CheckConstraint(condition=models.Q(('position__lte', 4)), name='max_position_4')],
            },
        ),
    ]
