# Generated by Django 5.1.3 on 2026-03-19 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_settings_pricing_and_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionAdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(db_index=True, max_length=50)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_admin_audits', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_audit_logs', to='subscription.userbooksubscription')),
            ],
            options={
                'verbose_name': 'Адмінський аудит підписки',
                'verbose_name_plural': 'Адмінські аудити підписок',
                'ordering': ['-created_at'],
            },
        ),
    ]
