# Generated by Django 5.1.3 on 2026-03-19 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_advertising_batch_and_indexes'),
        ('subscription', '0004_usage_restored_refunded_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooksubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Активний'), ('exhausted', 'Вичерпано'), ('expired', 'Закінчився'), ('cancelled', 'Скасовано'), ('refunded', 'Повернено кошти')], db_index=True, default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='UserChapterAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('balance_purchase', 'Balance purchase'), ('prepaid_subscription', 'Prepaid subscription'), ('instant_bulk_apply', 'Instant bulk apply'), ('admin_restore', 'Admin restore')], max_length=32)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_accesses', to='catalog.book')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='catalog.chapter')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapter_accesses', to='subscription.userbooksubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ до глави',
                'verbose_name_plural': 'Доступи до глав',
                'constraints': [models.UniqueConstraint(fields=('user', 'chapter'), name='uniq_user_chapter_access')],
            },
        ),
    ]
