# Generated by Django 5.1.3 on 2026-03-20 19:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_plan_discount_and_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booksubscriptionplan',
            options={'ordering': ['sort_order', 'discount_threshold'], 'verbose_name': 'План підписки', 'verbose_name_plural': 'Плани підписки'},
        ),
        migrations.AlterField(
            model_name='booksubscriptionplan',
            name='chapters_count',
            field=models.PositiveIntegerField(help_text='Зберігається для backward compat, використовується discount_threshold', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кількість розділів'),
        ),
        migrations.AlterField(
            model_name='booksubscriptionplan',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Знижка %'),
        ),
        migrations.AlterField(
            model_name='booksubscriptionplan',
            name='discount_threshold',
            field=models.PositiveIntegerField(default=10, verbose_name='Поріг (від N розділів)'),
        ),
        migrations.AlterField(
            model_name='booksubscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активовано'),
        ),
        migrations.AlterField(
            model_name='booksubscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Для backward compat; нова логіка рахує з цін глав', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ціна (FanCoins, legacy)'),
        ),
        migrations.AlterField(
            model_name='booksubscriptionplan',
            name='purchase_mode',
            field=models.CharField(choices=[('prepaid', 'Пакет (prepaid)'), ('instant', 'Миттєва покупка обраних')], db_index=True, default='prepaid', max_length=20, verbose_name='Режим покупки'),
        ),
    ]
