# Generated by Django 5.1.3 on 2026-03-20 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_unique_active_plans_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booksubscriptionplan',
            options={'ordering': ['sort_order', 'discount_threshold', 'id'], 'verbose_name': 'План підписки', 'verbose_name_plural': 'Плани підписки'},
        ),
        migrations.RemoveField(
            model_name='booksubscriptionsettings',
            name='allow_individual_purchase',
        ),
        migrations.RemoveField(
            model_name='booksubscriptionsettings',
            name='allow_instant_apply',
        ),
        migrations.RemoveField(
            model_name='booksubscriptionsettings',
            name='allow_prepaid_pack',
        ),
        migrations.RemoveField(
            model_name='booksubscriptionsettings',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='booksubscriptionsettings',
            name='discount_threshold',
        ),
        migrations.RemoveField(
            model_name='booksubscriptionsettings',
            name='price_per_chapter',
        ),
    ]
