# Generated by Django 5.1.3 on 2026-01-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('book_ratings_count', models.IntegerField(default=0)),
                ('translation_ratings_count', models.IntegerField(default=0)),
                ('comment_likes_count', models.IntegerField(default=0)),
                ('bookmarks_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('book_ratings', models.IntegerField(default=0)),
                ('translation_ratings', models.IntegerField(default=0)),
                ('comment_likes', models.IntegerField(default=0)),
                ('bookmarks', models.IntegerField(default=0)),
            ],
        ),
    ]
