# Generated by Django 5.1.3 on 2026-01-25 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics_books', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookanalytics',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='catalog.book'),
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='catalog.book'),
        ),
        migrations.AddIndex(
            model_name='dailyanalytics',
            index=models.Index(fields=['date'], name='analytics_b_date_712cac_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyanalytics',
            index=models.Index(fields=['book', 'date'], name='analytics_b_book_id_7ae8fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyanalytics',
            unique_together={('book', 'date')},
        ),
    ]
