# Generated by Django 5.1.3 on 2026-03-21 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_books', '0004_remove_duplicate_cleanup_periodic_task'),
        ('catalog', '0008_chapter_created_at_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLikeAnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('delta', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.book')),
            ],
            options={
                'indexes': [models.Index(fields=['book', 'day'], name='analytics_b_book_id_b8c0f7_idx')],
            },
        ),
    ]
