# Generated by Django 5.1.3 on 2026-04-05 20:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'sender', 'created_at'], name='msg_chat_sender_created_idx'),
        ),
    ]
