# Generated by Django 5.1.3 on 2026-05-08 17:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('stripe_event_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'processed_at'], name='idx_webhook_event_type_time')],
            },
        ),
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_session_id', models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=128, null=True)),
                ('amount_coins', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_kopecks', models.PositiveIntegerField()),
                ('currency', models.CharField(default='uah', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('expired', 'expired'), ('failed', 'failed')], db_index=True, default='pending', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_pay_sess_status_created')],
                'constraints': [models.UniqueConstraint(fields=('user', 'stripe_session_id'), name='uniq_payment_session_user_stripe_session')],
            },
        ),
    ]
