# Generated by Django 5.1.3 on 2026-05-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentsession',
            options={'verbose_name': 'Платіжна сесія', 'verbose_name_plural': 'Платіжні сесії'},
        ),
        migrations.AlterModelOptions(
            name='webhookevent',
            options={'verbose_name': 'Webhook-подія', 'verbose_name_plural': 'Webhook-події'},
        ),
    ]
