# Generated by Django 5.1.3 on 2026-07-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsession',
            name='service_fee_uah',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сервісний збір (UAH)'),
        ),
    ]
