# Generated by Django 5.1.3 on 2026-04-05 11:42

import apps.support.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, db_index=True, editable=False, max_length=32, null=True, unique=True, verbose_name='Номер звернення')),
                ('name', models.CharField(max_length=120, verbose_name="Ім'я / нік")),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('category', models.CharField(choices=[('technical', 'Технічна проблема'), ('payment', 'Питання по платежам'), ('content', 'Питання по контенту'), ('account', 'Проблеми з акаунтом'), ('other', 'Інше')], db_index=True, max_length=32, verbose_name='Категорія')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('status', models.CharField(choices=[('new', 'Новий'), ('in_progress', 'В роботі'), ('closed', 'Закритий')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низький'), ('normal', 'Звичайний'), ('high', 'Високий'), ('urgent', 'Терміновий')], db_index=True, default='normal', max_length=20, verbose_name='Пріоритет')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Коментар адміністратора')),
                ('source', models.CharField(db_index=True, default='support_page', max_length=64, verbose_name='Джерело')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('http_referer', models.CharField(blank=True, max_length=512, verbose_name='Referer')),
                ('submitted_page_url', models.CharField(blank=True, max_length=500, verbose_name='Сторінка (клієнт)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Звернення в підтримку',
                'verbose_name_plural': 'Звернення в підтримку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.support.models.support_attachment_upload_to, verbose_name='Файл')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Оригінальна назва')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Завантажено')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.supportticket', verbose_name='Звернення')),
            ],
            options={
                'verbose_name': 'Вкладення',
                'verbose_name_plural': 'Вкладення',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Було')),
                ('new_status', models.CharField(max_length=20, verbose_name='Стало')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Час зміни')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хто змінив')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='support.supportticket', verbose_name='Звернення')),
            ],
            options={
                'verbose_name': 'Історія статусу',
                'verbose_name_plural': 'Історія статусів',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['-created_at', 'status'], name='support_sup_created_9d97e6_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['email', '-created_at'], name='support_sup_email_df3cdb_idx'),
        ),
    ]
