# Generated by Django 5.1.3 on 2026-06-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('technical', 'Технічна проблема'), ('payment', 'Питання по платежам'), ('content', 'Питання по контенту'), ('account', 'Проблеми з акаунтом'), ('suggestions', 'Пропозиції та побажання'), ('other', 'Інше')], db_index=True, max_length=32, verbose_name='Категорія'),
        ),
    ]
