# Generated by Django 5.1.3 on 2026-05-17 10:20

import apps.payouts.fields
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_balancelog_operation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='payouts/batches/%Y/%m/')),
                ('total_amount_by_currency', models.JSONField(default=dict)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('csv_generated', 'CSV згенеровано'), ('sent_to_wise', 'Завантажено у Wise'), ('confirmed', 'Усі виплати пройшли'), ('partial', 'Частково виплачено'), ('failed', 'Не вдалось')], default='draft', max_length=16)),
                ('wise_batch_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('csv_generated_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch виплат',
                'verbose_name_plural': 'Batches виплат',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_status', models.CharField(choices=[('individual', 'Фізособа без бізнес-статусу'), ('fop_ua', 'ФОП (Україна)'), ('self_employed_other', 'Самозайнятий (інша країна)'), ('legal_entity', 'Юр. особа')], default='individual', max_length=32)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2: UA, CZ, DE, IT, US', max_length=2)),
                ('tax_residency_country', models.CharField(help_text='Країна податкового резидентства', max_length=2)),
                ('tax_id', models.CharField(blank=True, help_text='РНОКПП, DIČ, Codice Fiscale, SSN/ITIN', max_length=64)),
                ('tax_residency_certificate', models.FileField(blank=True, null=True, upload_to='payouts/tax_certs/%Y/%m/')),
                ('full_name_legal', models.CharField(help_text='ПІБ як у паспорті', max_length=200)),
                ('full_name_latin', models.CharField(help_text='ПІБ латиницею', max_length=200)),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('verification_status', models.CharField(choices=[('draft', 'Чернетка (не подано на перевірку)'), ('pending', 'Очікує перевірки'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено'), ('requires_more_info', 'Потрібна додаткова інформація')], db_index=True, default='draft', max_length=32)),
                ('verification_notes', models.TextField(blank=True)),
                ('payout_approved', models.BooleanField(default=False, help_text='Чи дозволено отримувати виплати')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профіль виплат',
                'verbose_name_plural': 'Профілі виплат',
            },
        ),
        migrations.CreateModel(
            name='PayoutMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('wise_iban', 'Wise (IBAN)')], default='wise_iban', max_length=32)),
                ('iban', apps.payouts.fields.EncryptedCharField(max_length=256)),
                ('bic_swift', apps.payouts.fields.EncryptedCharField(blank=True, max_length=256)),
                ('recipient_full_name', models.CharField(max_length=200)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=True)),
                ('iban_changed_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('successful_payouts_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='payouts.payoutprofile')),
            ],
            options={
                'verbose_name': 'Метод виплати',
                'verbose_name_plural': 'Методи виплат',
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_coins', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coins_after_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payout_currency', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('amount_gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('withholding_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('withholding_tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('snapshot_recipient_name', models.CharField(max_length=200)),
                ('snapshot_iban', apps.payouts.fields.EncryptedCharField(max_length=256)),
                ('snapshot_bic_swift', apps.payouts.fields.EncryptedCharField(blank=True, max_length=256)),
                ('snapshot_method_type', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Подано, очікує автоперевірки'), ('awaiting_review', 'На ручній перевірці'), ('approved', 'Схвалено, готовий до batch'), ('in_batch', 'Включений у batch'), ('processing', 'Відправлений у Wise'), ('completed', 'Виплачено'), ('failed', 'Wise відхилив'), ('cancelled', 'Скасовано')], db_index=True, default='pending', max_length=20)),
                ('wise_transfer_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('auto_check_result', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('invoice_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='payouts/invoices/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auto_checked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(help_text="Дата до якої зобов'язані відправити (created_at + 14 днів)")),
                ('balance_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout_request', to='users.balancelog')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='payouts.payoutbatch')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_requests', to='payouts.payoutmethod')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_requests', to='payouts.payoutprofile')),
            ],
            options={
                'verbose_name': 'Запит на виплату',
                'verbose_name_plural': 'Запити на виплати',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payoutprofile',
            index=models.Index(fields=['verification_status', 'payout_approved'], name='payouts_pay_verific_a01e4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='payoutmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('profile',), name='unique_default_active_method_per_profile'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['status', 'deadline_at'], name='payouts_pay_status_a79bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['profile', 'status'], name='payouts_pay_profile_0da857_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['status', 'created_at'], name='payouts_pay_status_73decb_idx'),
        ),
    ]
