# Generated by Django 5.1.3 on 2026-05-22 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0005_security_fixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wisewebhookdelivery',
            new_name='payouts_wis_receive_9920ee_idx',
            old_name='payouts_wis_receive_idx',
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Адмін, який схвалив запит', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Подано'), ('awaiting_review', 'На перевірці'), ('approved', 'Схвалено, готовий до batch'), ('in_batch', 'Включений у batch'), ('processing', 'Відправлений у Wise'), ('completed', 'Виплачено'), ('failed', 'Wise відхилив'), ('cancelled', 'Скасовано')], db_index=True, default='pending', max_length=20),
        ),
    ]
