# Generated by Django 5.1.3 on 2026-05-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0006_add_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='is_urgent',
            field=models.BooleanField(db_index=True, default=False, help_text='Терміновий вивід (комісія 10%, дедлайн 3 дні)'),
        ),
    ]
