# Generated by Django 5.1.3 on 2026-05-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0007_add_is_urgent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payoutbatch',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пакет batch для Wise (CSV)', 'verbose_name_plural': 'Пакети batch для Wise (CSV)'},
        ),
        migrations.AlterModelOptions(
            name='payoutrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запит на виплату', 'verbose_name_plural': 'Усі заявки на виплату'},
        ),
        migrations.AlterField(
            model_name='payoutbatch',
            name='completed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Виконано'),
        ),
        migrations.AlterField(
            model_name='payoutbatch',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Підтверджено'),
        ),
        migrations.AlterField(
            model_name='payoutbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='payoutbatch',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='payouts/batches/%Y/%m/', verbose_name='CSV-файл'),
        ),
        migrations.AlterField(
            model_name='payoutbatch',
            name='csv_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CSV згенеровано'),
        ),
        migrations.AlterField(
            model_name='payoutbatch',
            name='failed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Помилки'),
        ),
        migrations.AlterField(
            model_name='payoutbatch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='payoutbatch',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примітки'),
        ),
        migrations.AlterField(
            model_name='payoutbatch',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Відправлено у Wise'),
        ),
        migrations.AlterField(
            model_name='payoutbatch',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('csv_generated', 'CSV згенеровано'), ('sent_to_wise', 'Завантажено у Wise'), ('confirmed', 'Усі виплати пройшли'), ('partial', 'Частково виплачено'), ('failed', 'Не вдалось')], default='draft', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='payoutbatch',
            name='total_amount_by_currency',
            field=models.JSONField(default=dict, verbose_name='Суми за валютами'),
        ),
        migrations.AlterField(
            model_name='payoutbatch',
            name='total_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість заявок'),
        ),
        migrations.AlterField(
            model_name='payoutbatch',
            name='wise_batch_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Референс Wise'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='amount_gross',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума брутто'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='amount_net',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума нетто'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Схвалено'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='auto_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Автоперевірка'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='coins_after_commission',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Після комісії (coins)'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='coins_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума (coins)'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='commission_coins',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Комісія (coins)'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% комісії'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Виплачено'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='deadline_at',
            field=models.DateTimeField(help_text="Дата до якої зобов'язані відправити (created_at + 14 днів)", verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Курс обміну'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='is_urgent',
            field=models.BooleanField(db_index=True, default=False, help_text='Терміновий вивід (комісія 10%, дедлайн 3 дні)', verbose_name='Терміново'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='payout_currency',
            field=models.CharField(max_length=3, verbose_name='Валюта виплати'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Відправлено у Wise'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Подано'), ('awaiting_review', 'На перевірці'), ('approved', 'Схвалено, готовий до batch'), ('in_batch', 'Включений у batch'), ('processing', 'Відправлений у Wise'), ('completed', 'Виплачено'), ('failed', 'Wise відхилив'), ('cancelled', 'Скасовано')], db_index=True, default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='wise_transfer_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID переказу Wise'),
        ),
    ]
