# Generated by Django 5.1.3 on 2026-06-23 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0008_alter_payoutbatch_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPayoutRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Нова заявка на виплату',
                'verbose_name_plural': 'Нові заявки на виплату',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payouts.payoutrequest',),
        ),
    ]
